# Generated by Django 4.0.4 on 2023-11-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_products_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='review',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
