# Generated by Django 4.0.4 on 2024-03-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_rename_status_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='status',
        ),
    ]
