# Generated by Django 4.0.4 on 2024-03-11 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0006_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_review',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainPage.customer'),
        ),
    ]
