# Generated by Django 4.2.11 on 2024-03-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0010_alter_meettheteam_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='material',
        ),
        migrations.RemoveField(
            model_name='products',
            name='overview',
        ),
        migrations.CreateModel(
            name='Products_overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.products')),
            ],
        ),
        migrations.CreateModel(
            name='Products_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.products')),
            ],
        ),
    ]
